apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ app_name }}
  namespace: {{ model_name }}
spec:
  gatewayClassName: istio
  listeners:
  - name: default
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
