apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ app_name }}
  namespace: {{ model_name }}
spec:
  parentRefs:
  - name: {{ gateway_name }}
    namespace: {{ gateway_model_name }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: {{ prefix }}
{% if strip_prefix %}
    filters:
      - type: URLRewrite
        urlRewrite:
          path:
            type: ReplacePrefixMatch
            replacePrefixMatch: /
{% endif %}
    backendRefs:
    - name: {{ requester_svc }}
      port: {{ requester_port }}
      namespace: {{ model_name }}
# Do we want to use the k8s headless svc and let gateway api to do the load balancing
# Or maybe use the normal clusterIP service and let k8s do the load balancing
    # backendRefs:
    # {% for svc in requester_svc %}
    # - name: {{ svc }}
    #   port: {{ requester_port }}
    #   namespace: {{ model_name }}
    # {% endfor %}